### ISSUE TITLE
[MultiSemaphore] ReplyError: ERR Error running script: @user_script:18: user_script:18: too many results to unpack

### ISSUE THREAD

**Issue by SeverinAlexB** [swarthy/redis-semaphore#28]
I get a weird error when I  call `.aquire()` with more than 3999 permits.

```ts
const resource = 'x';
const maxPermits = 5000;
const permitsToAquire = 4000;
const semaphore = new MultiSemaphore(redisClient, resource, maxPermits, permitsToAquire);
await semaphore.acquire();  // Error
```

Error:
```
ReplyError: ERR Error running script (call to f_10c1c2e05e7c48aa5824d227b8c51abcde87b18e): @user_script:18: user_script:18: too many results to unpack
    at parseError (/Users/severinbuhler/git/lnroute/ln-route-node/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/severinbuhler/git/lnroute/ln-route-node/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      '10c1c2e05e7c48aa5824d227b8c51abcde87b18e',
      '1',
      'semaphore:x',
      '5000',
      '4000',
      '372c2438-ac42-4376-84d2-4327dd648684',
      '20000',
      '1625537113196'
    ]
  }
}
```

At the moment, `MultiSemaphore` is not usable with more than 4000+ permits. It would be great to get some help :)

Best regards
Severin

**Comment by swarthy** [comment]
Hi! Sorry for long response.
Semaphore in this lib was designed for much less value for maxPermits (5-100). I guess you should use something more robust for your task than Redis + this lib.

**Comment by SeverinAlexB** [comment]
Okkk, not sure if there is library for distributed Semaphores with permits for js out there other than this. Let' see
